import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

async function readSource(relativePath) {
  return readFile(new URL(relativePath, import.meta.url), 'utf8')
}

test('gallery route uses the read-only feature hook and archive view', async () => {
  const galleryPageSource = await readSource('../pages/GalleryPage.jsx')
  const galleryViewSource = await readSource('../features/gallery/GalleryView.jsx')
  const galleryDataSource = await readSource('../features/gallery/useGalleryData.js')
  const mediaIndexSource = await readSource('../features/gallery/useMediaIndexSource.js')

  assert.match(galleryPageSource, /useGalleryData/)
  assert.match(galleryPageSource, /GalleryView/)
  assert.match(galleryDataSource, /useMediaIndexSource/)
  assert.match(galleryDataSource, /buildGalleryReadModelWithMediaIndex/)
  assert.match(mediaIndexSource, /getFirestoreMediaIndexForCouple/)
  assert.match(mediaIndexSource, /DATA_SOURCE_MODES\.firestore/)
  assert.match(mediaIndexSource, /UNAVAILABLE_MEDIA_INDEX_SOURCE/)
  assert.doesNotMatch(mediaIndexSource, /throw new Error\('Media index requires/)
  assert.doesNotMatch(galleryPageSource, /PlaceholderPage/)
  assert.match(galleryViewSource, /cb-album-header/)
  assert.match(galleryViewSource, /cb-media-viewer/)
  assert.match(galleryViewSource, /model\.items/)
  assert.match(galleryViewSource, /useGoogleDriveConnection/)
  assert.match(galleryViewSource, /useMediaUploadQueue/)
  assert.match(galleryViewSource, /Prepare photos and videos/)
  assert.match(galleryViewSource, /Start uploads/)
  assert.match(galleryViewSource, /Upload setup required/)
  assert.match(galleryViewSource, /owner media setup in Settings/i)
  assert.match(galleryViewSource, /Queue is empty/)
  assert.match(galleryViewSource, /MediaPreview/)
  assert.match(galleryViewSource, /MediaPreview/)
  assert.doesNotMatch(galleryViewSource, /Album media access/)
  assert.match(galleryViewSource, /gallery-media-library-grid/)
  assert.match(galleryViewSource, /gallery-index-tile/)
  assert.match(galleryViewSource, /drive-indexed/)
  assert.match(galleryViewSource, /mediaTileAspectStyle/)
  assert.doesNotMatch(galleryViewSource, /Manage Media & Sync/)
  assert.doesNotMatch(galleryViewSource, /Album will not open a Google OAuth popup/)
  assert.doesNotMatch(galleryViewSource, /Shared media service/)
  assert.doesNotMatch(galleryViewSource, /Deployment approval required/)
  assert.doesNotMatch(galleryViewSource, /18\/18|LOCAL BACKEND HANDLERS READY|trusted Drive backend handler capabilities/)
  assert.doesNotMatch(galleryViewSource, /Connect Google Drive|DriveMediaGrid|Private folder previews|thumbnailLink/)
  assert.doesNotMatch(galleryViewSource, /iCloud|LIVE_SHARED_ALBUM|Live Album/)
})

test('gallery view keeps verified private media boundaries and uses the modular CSS entrypoint', async () => {
  const galleryViewSource = await readSource('../features/gallery/GalleryView.jsx')
  const mainSource = await readSource('../main.jsx')
  const tokensSource = await readSource('../styles/tokens.css')
  const navigationSource = await readSource('../styles/navigation.css')

  assert.match(galleryViewSource, /function galleryTileLabel\(item\)/)
  assert.match(galleryViewSource, /aria-label=\{selectionMode \? .*galleryTileLabel\(item\).* : galleryTileLabel\(item\)\}/)
  assert.match(galleryViewSource, /aria-pressed=\{selectionMode \? selected : undefined\}/)
  assert.match(galleryViewSource, /storage-verified/)
  assert.doesNotMatch(galleryViewSource, /Connect to add files|Connect Google Drive/)
  assert.doesNotMatch(galleryViewSource, /Private media provider|Google Drive connection/)
  assert.match(mainSource, /import '\.\/styles\/pages\/album\.css'/)
  assert.match(mainSource, /import '\.\/styles\/pages\/media-upload\.css'/)
  assert.match(tokensSource, /--cb-color-primary:/)
  assert.match(navigationSource, /safe-area-inset-bottom/)
  assert.doesNotMatch(galleryViewSource, /createObjectURL|fetch\(|uploadBytes|firebase\/storage/)
  assert.doesNotMatch(galleryViewSource, /pages\/media\.html|pages\/gallery\.html|js\/media\.js|legacy\.html|pageUrl|mediaPath/)
  assert.doesNotMatch(galleryViewSource, /localStorage|memorybook_|legacyMemoryAdapter|raw warnings/)
  assert.doesNotMatch(galleryViewSource, /\bsetItem\s*\(|\bupdateDoc\s*\(|\baddDoc\s*\(|\bdeleteDoc\s*\(/)
  assert.doesNotMatch(galleryViewSource, /iCloud|LIVE_SHARED_ALBUM|Live Album/)
})
