import { LEGACY_LOCAL_DEV_SOURCE, LEGACY_LOCAL_STORAGE_SOURCE } from '../data/adapterUtils.js'

export const browserRegressionAuthorizedFixture = Object.freeze({
  enabled: true,
  auth: Object.freeze({
    status: 'authorized',
    user: Object.freeze({
      uid: 'browser-test-approved-reader',
      email: 'approved-reader@example.com',
      displayName: 'Approved Reader',
      metadata: Object.freeze({
        lastSignInTime: '2026-07-14T12:34:56.000Z',
      }),
    }),
    approvedUser: Object.freeze({
      username: 'Reader',
      displayName: 'Approved Reader',
      profileName: 'Approved Reader',
    }),
  }),
  compatibility: Object.freeze({
    state: 'ready',
    snapshot: Object.freeze({
      status: 'ready',
      sources: Object.freeze({
        settings: Object.freeze({
          status: 'ready',
          source: LEGACY_LOCAL_STORAGE_SOURCE,
          data: Object.freeze({
            username: 'Reader',
            theme: 'sunset',
            usedGlobalThemeFallback: false,
            settings: Object.freeze({
              anniversaryConfig: 'dual',
              privacyToggles: Object.freeze({
                localOnlyMode: true,
                hideOfflineWarning: false,
                unknownFields: Object.freeze({}),
              }),
              unknownFields: Object.freeze({}),
            }),
          }),
          warnings: Object.freeze([]),
        }),
        profile: Object.freeze({
          status: 'ready',
          source: LEGACY_LOCAL_STORAGE_SOURCE,
          data: Object.freeze({
            participantOrder: Object.freeze(['Reader', 'Partner']),
            profilesByUsername: Object.freeze({
              Reader: Object.freeze({
                name: 'Approved Reader',
                bio: '',
                avatar: '',
                anniversaryView: 'dual',
                joinedDate: '2026-02-14',
                birthday: null,
                unknownFields: Object.freeze({}),
              }),
              Partner: Object.freeze({
                name: 'Partner Record',
                bio: '',
                avatar: '',
                anniversaryView: 'partner',
                joinedDate: '2026-02-14',
                birthday: null,
                unknownFields: Object.freeze({}),
              }),
            }),
            unknownTopLevelFields: Object.freeze({}),
          }),
          warnings: Object.freeze([]),
        }),
        favorites: Object.freeze({
          status: 'ready',
          source: LEGACY_LOCAL_STORAGE_SOURCE,
          data: Object.freeze({
            books: ['Fictional keepsake'],
          }),
          warnings: Object.freeze([]),
        }),
        contract: Object.freeze({
          status: 'ready',
          source: LEGACY_LOCAL_STORAGE_SOURCE,
          data: Object.freeze({
            username: 'Reader',
            accepted: true,
            activeSignature: Object.freeze({
              accepted: true,
              timestamp: '2026-07-14T00:00:00.000Z',
              version: 'fixture-3',
              history: Object.freeze([]),
              unknownFields: Object.freeze({}),
              hasLegacyPayload: true,
              redactedFields: Object.freeze(['signature-data']),
            }),
            signaturesByUsername: Object.freeze({
              Reader: Object.freeze({
                accepted: true,
                timestamp: '2026-07-14T00:00:00.000Z',
                version: 'fixture-3',
                history: Object.freeze([]),
                unknownFields: Object.freeze({}),
                hasLegacyPayload: true,
                redactedFields: Object.freeze(['signature-data']),
              }),
              Partner: Object.freeze({
                accepted: false,
                timestamp: null,
                version: 'fixture-3',
                history: Object.freeze([]),
                unknownFields: Object.freeze({}),
                hasLegacyPayload: false,
                redactedFields: Object.freeze([]),
              }),
            }),
          }),
          warnings: Object.freeze([]),
        }),
        memories: Object.freeze({
          status: 'ready',
          source: LEGACY_LOCAL_DEV_SOURCE,
          data: Object.freeze({
            hasBaseDataset: true,
            customMemoryCount: 0,
            overriddenMemoryCount: 0,
            deletedMemoryCount: 0,
            memories: Object.freeze([
              Object.freeze({
                id: 'browser-fictional-special',
                title: 'Fictional protected moment',
                description: 'A fictional special moment used only for browser regression.',
                dateLabel: '2026-05-14',
                tags: Object.freeze(['special']),
                mediaKind: 'unknown',
                mediaPath: '',
                isSpecialPage: true,
                pageUrl: 'valentine/index.html',
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-photo-1',
                title: 'Fictional photo chapter one',
                description: 'A fictional photo entry used only for browser regression.',
                dateLabel: '2026-05-10',
                tags: Object.freeze(['fictional']),
                mediaKind: 'image',
                mediaPath: '/assets/photos/browser-fictional-one.jpg',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-video-1',
                title: 'Fictional video chapter',
                description: 'A fictional video entry used only for browser regression.',
                dateLabel: '2026-05-09',
                tags: Object.freeze(['fictional']),
                mediaKind: 'video',
                mediaPath: '/assets/videos/browser-fictional-one.mp4',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-photo-2',
                title: 'Fictional photo chapter two',
                description: 'A fictional photo entry used only for browser regression.',
                dateLabel: '2026-05-08',
                tags: Object.freeze(['fictional']),
                mediaKind: 'image',
                mediaPath: '/assets/photos/browser-fictional-two.jpg',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-photo-3',
                title: 'Fictional photo chapter three',
                description: 'A fictional photo entry used only for browser regression.',
                dateLabel: '2026-05-07',
                tags: Object.freeze(['fictional']),
                mediaKind: 'image',
                mediaPath: '/assets/photos/browser-fictional-three.jpg',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-photo-4',
                title: 'Fictional photo chapter four',
                description: 'A fictional photo entry used only for browser regression.',
                dateLabel: '2026-05-06',
                tags: Object.freeze(['fictional']),
                mediaKind: 'image',
                mediaPath: '/assets/photos/browser-fictional-four.jpg',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
              Object.freeze({
                id: 'browser-fictional-photo-5',
                title: 'Fictional photo chapter five',
                description: 'A fictional photo entry used only for browser regression.',
                dateLabel: '2026-05-05',
                tags: Object.freeze(['fictional']),
                mediaKind: 'image',
                mediaPath: '/assets/photos/browser-fictional-five.jpg',
                isSpecialPage: false,
                pageUrl: null,
                source: 'static-json',
                unknownFields: Object.freeze({}),
              }),
            ]),
          }),
          warnings: Object.freeze([]),
        }),
      }),
      warnings: Object.freeze([]),
    }),
    error: '',
  }),
})

export const browserRegressionSignedOutFixture = Object.freeze({
  enabled: true,
  auth: Object.freeze({
    status: 'signed-out',
  }),
})

export const browserRegressionUnavailableTimelineFixture = Object.freeze({
  enabled: true,
  auth: browserRegressionAuthorizedFixture.auth,
  compatibility: Object.freeze({
    state: 'ready',
    snapshot: Object.freeze({
      status: 'ready',
      sources: Object.freeze({
        memories: Object.freeze({
          status: 'unavailable',
          source: LEGACY_LOCAL_DEV_SOURCE,
          data: null,
          warnings: Object.freeze(['Legacy local memory bridge is disabled.']),
        }),
      }),
      warnings: Object.freeze([]),
    }),
    error: '',
  }),
})
